{
 "title": "SSH Sessions",
 "description": "Overview of SSH session activity intended for personal servers",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current SSH Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ssh_num_sessions{remote_ip!=\"-\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Local Sessions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ssh_num_sessions{remote_ip=\"localhost\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    { "expr": "sum(ssh_num_sessions)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SSH Sessions per IP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "ssh_num_sessions{remote_ip!=\"-\", job=\"ssh\"}",
     "legendFormat": "{{ remote_ip }}"
    }
   ]
  },
  {
   "title": "List of current Sessions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(remote_ip) (ssh_num_sessions)",
     "legendFormat": "{{remote_ip}}"
    }
   ]
  }
 ]
}